
FORMAT: 1A
HOST: http://alefba.sobhe.ir

# الفبا

<div dir=rtl>
نویسه‌خوان الفبا تصویر اسناد فارسی، انگلیسی و عربی را می‌خواند و در قالب متن مرتب ارائه می‌دهد.
</div>

<blockquote dir=rtl>
برای دسترسی به واسط برنامه‌نویس الفبا نیاز به یک TOKEN_KEY معتبر دارید که برای احراز هویت استفاده می‌شود. لطفا برای آزمایش سامانه، این متغیر را در تقاضاهای نمونه، جای‌گذاری کنید. سوال هم اگر دارید، لطفا برای آدرس alefba@sobhe.ir بنویسید.
</blockquote>


## خواندن سند [/api/read_document/]

<div dir=rtl>
این تابع، یک سند را دریافت می‌کند و متن صفحات آن را در قالب JSON باز می‌گرداند. خروجی نویسه‌خوان شامل بخش‌های نوشته (پاراگراف)، جدول و تصویر است. مکان و ابعاد هر بخش در خروجی مشخص شده است و اطلاعات کامل خطوط متن در بخش نوشته ظاهر می‌شود. برای هر خط متن، ویژگی احتمال صحت هم قرار داده شده که نشان می‌دهد ابزار نویسه‌خوان چقدر از نتیجه تحلیل، مطمئن است.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل سند را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "document=@example.pdf" http://alefba.sobhe.ir/api/read_document

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "word_positions": false,
              "wait": true
            }

+ Response 200 (application/json)

        {
          "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "width": 2125,
            "height": 2750,
            "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "209 305 1711 449",
                "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "211 305 1707 57",
                    "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                  },
                  ...
                ]
              },
              ...
            ]
          },{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2",
            "width": 2125,
            "height": 2750,
            "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "210 110 1714 294",
                "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "210 110 1706 58",
                    "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین"
                  },
                  ...
                ],
              },
              ...
            ]
          }]
        }


## خواندن صفحه [/api/read_pages/]

<div dir=rtl>
این تابع، تصویر نوشته را دریافت می‌کند و متن آن را در قالب JSON باز می‌گرداند. خروجی نویسه‌خوان شامل بخش‌های نوشته (پاراگراف)، جدول و تصویر است. مکان و ابعاد هر بخش در خروجی مشخص شده است و اطلاعات کامل خطوط متن در بخش نوشته ظاهر می‌شود. برای هر خط متن، ویژگی احتمال صحت هم قرار داده شده که نشان می‌دهد ابزار نویسه‌خوان چقدر از نتیجه تحلیل، مطمئن است.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل صفحه را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "page=@example.jpg" http://alefba.sobhe.ir/api/read_pages

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "page_urls": ["http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1"],
              "word_positions": false,
              "wait": true
            }

+ Response 200 (application/json)

        [{
          "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
          "width": 2125,
          "height": 2750,
          "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
          "parts": [
            {
              "type": "text",
              "direction": "rtl",
              "box": "209 305 1711 449",
              "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
              "lines": [
                {
                  "probability": 1.0,
                  "box": "211 305 1707 57",
                  "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                },
                ...
              ]
            },
            ...
          ]
        }]


## صفحات سند [/api/document_pages/]

<div dir=rtl>
نویسه‌خوان برای تحلیل سند، ابتدا باید آن را صفحه‌صفحه کند. این تابع، فایل سند را در قالب PDF دریافت می‌کند و صفحات آن را به عنوان نتیجه باز می‌گرداند. بعد از این مرحله، تابع «خواندن صفحه» می‌تواند هر کدام از صفحه‌های سند را تحلیل کند.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل سند را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "document=@example.pdf" http://alefba.sobhe.ir/api/document_pages

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/json)

        {
          "document_url":"http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2"
          ]
        }


## دریافت فایل ورد [/api/download_word/]

<div dir=rtl>
با استفاده از این تابع می‌توانید نتیجه صفحات پردازش شده را در قالب فایل Microsoft Word دریافت نمایید. در فایل خروجی، قالب سند حفظ شده است و اجزای متن شامل خطوط، پاراگراف‌ها و خانه‌های جدول در جای خود قرار گرفته‌اند.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/msword)

    + Header

            Content-Disposition: attachment; filename=Alefba.docx

    + Body


## دریافت فایل قابل جستجو [/api/download_pdf/]

<div dir=rtl>
با استفاده از این تابع می‌توانید نتیجه صفحات پردازش شده را در قالب فایل PDF دریافت نمایید. فایل خروجی، تصاویر صفحات سند ورودی را به همراه نتیجه پردازش آنها نشان می‌دهد. به این ترتیب با جستجوی یک عبارت در این فایل، واژه‌های مورد جستجو در تصویر مشخص و رنگی می‌شوند.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "quality": 100,
              "img_format": "png"
            }

+ Response 200 (application/pdf)

    + Header

            Content-Disposition: attachment; filename=Alefba.pdf

    + Body


## حذف سند [/api/delete_document/]

<div dir=rtl>
با استفاده از این تابع می‌توانید سند ثبت شده در سامانه را به طور کامل حذف کنید.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/json)

        {
          "message":"Document deleted successfully."
        }
