
FORMAT: 1A
HOST: http://api.sobhe.ir:7000/

# باز

<div dir=rtl>
باز قرار است تجربه جستجوی هوشمند را برای خدمات وب فارسی فراهم کند تا مخاطب آسان‌تر به نتیجه مطلوب برسد.
</div>

<blockquote dir=rtl>
برای دسترسی به واسط برنامه‌نویس باز، نیاز به یک TOKEN_KEY معتبر دارید که برای احراز هویت استفاده می‌شود. لطفا برای آزمایش سامانه، این متغیر را در تقاضاهای نمونه، جای‌گذاری کنید. سوال هم اگر دارید، لطفا برای آدرس baaz@sobhe.ir بنویسید.
</blockquote>


## نمایه‌سازی [/{index_name}/index]

<div dir=rtl>
برای جستجوی اسناد ابتدا باید آنها را نمایه کنید. نمایه جستجو در واقع بخشی از پایگاه داده‌ها است که انتظار دارید، کاربر با نوشتن عبارت مورد نظر، نتیجه را از میان آنها پیدا کند.
</div>

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه


### ثبت داده‌ها [POST]

<div dir=rtl>
این تابع امکان افزودن اسناد به  نمایه را فراهم می‌کند. ورودی items برای این تابع، شامل فهرستی از اسناد است که هر کدام از آنها باید در نمایه ثبت شوند.
</div>

+ Request (application/json)

    + Attributes

        - type: movie (string, required) - این ویژگی نوع سند را مشخص می‌کند و برای محدود کردن دامنه جستجو استفاده می‌شود
        - id: 1 (number, required) - شناسه سند که در هر «نوع»، ویژگی یکتا محسوب می‌شود
        - title: ماجرای نیمروز (string, required) - عنوان سند که مهم‌ترین ویژگی متنی در رتبه‌بندی نتایج است
        - importance: 100 (number) - هر چه میزان اهمیت یک سند بالاتر باشد، رتبه آن در میان نتایج بالاتر است
        - time: `2017-07-08 10:30:00` (string) - هر چه زمان ایجاد سند به زمان حال نزدیکتر باشد، رتبه آن در میان نتایج بالاتر است
        - labels: هیجانی, ماجراجویی (array[string]) - مجموعه برچسب‌های سند که جستجو نمی‌شوند و فقط برای محدود کردن نتایج مورد استفاده قرار می‌گیرند
        - ...: ... (string) - هر ویژگی دیگری در قالب «نوشته» یا «نوشته‌ها» می‌تواند برای سند ثبت شود و مورد جستجو قرار گیرد

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "items": [
                    {
                        "type": "movie",
                        "id": 1,
                        "title": "ماجرای نیمروز",
                        "director": "محمدحسین مهدویان",
                        "actors": ["جواد عزتی", "هادی حجازی‌فر"],
                        "labels": ["هیجانی", "ماجراجویی"],
                        "importance": 100,
                        "data": {"url": "https://www.filimo.com/m/czWum"}
                    },
                    {
                        "type": "movie",
                        "id": 2,
                        "title": "ایستاده در غبار",
                        "director": "محمدحسین مهدویان",
                        "labels": ["هیجانی", "جنگی"],
                        "importance": 50,
                        "data": {"url": "https://www.filimo.com/m/fsa4n"}
                    },
                    {
                        "type": "person",
                        "id": 1,
                        "title": "ابراهیم حاتمی‌کیا",
                        "data": {"url": "https://www.filimo.com/crew/ابراهیم_حاتمی_کیا"}
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "ids": [1, 2, 1]
            }

### ویرایش داده‌ها [PUT]

<div dir=rtl>
این تابع امکان ویرایش اسناد ثبت‌شده را فراهم می‌کند. برای این منظور، کافیست داده‌های جدید به همراه type و id سند فرستاده شوند. توجه کنید که در هنگام به‌روزرسانی، فقط اطلاعات ارسال‌شده ذخیره می‌شوند و دیگر ویژگی‌های سند، تغییر نمی‌کنند.
</div>

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "items": [
                    {
                        "type": "movie",
                        "id": 1,
                        "importance": 200
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "ids": [1]
            }

### حذف داده‌ها [DELETE]

<div dir=rtl>
این تابع امکان حذف مجموعه‌ای از اسناد را فراهم می‌کند. ویژگی type نمایش‌دهنده نوع اسناد است و ids شناسه آنها را مشخص می‌کند.
</div>

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "type": "movie",
                "ids": [2]
            }

+ Response 200 (application/json)

    + Body

            {
                "ids": [2]
            }


## ‌ [/{index_name}/{types}/query{?fields,text,size,from}]

# جستجوی اسناد

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه
    + types: `movie|person` (required, string) - فهرست دسته‌ها که با نویسه خط (|) به هم متصل شده‌اند
    + text: `نیم‌روز` (required, string) - عبارت مورد جستجو
    + fields: `title|director` (optional, string) - فهرست ویژگی‌ها که با نویسه خط (|) به هم متصل شده‌اند
    + size: `10` (optional, number) - تعداد نتایج در پاسخ
    + from: `0` (optional, number) - نقطه شروع برای صفحه‌بندی نتایج

### جستجو [GET]

<div dir=rtl>
داده‌های نمایه‌شده با استفاده از این تابع قابل جستجو هستند. گاهی پیش می‌آید که کاربر عبارت مورد نظرش را اشتباه می‌نویسد؛ در این مواقع، پاسخ جستجو با ویژگی didYouMean همراه است که واژه‌های اصلاح‌شده، در آن با تگ‌های تاکید مشخص شده‌اند.
</div>

+ Response 200 (application/json)

        {
          "didYouMean": "<em>نیمروز</em>",
          "items": [
            {
              "type": "movie",
              "id": "1",
              "item": {
                "title": "ماجرای نیمروز",
                "director": "محمدحسین مهدویان",
                "labels": ["هیجانی", "ماجراجویی"],
                "actors": ["جواد عزتی", "هادی حجازی‌فر"],
                "importance": 100,
                "data": {"url": "https://www.filimo.com/m/czWum"}
              },
              "highlight": {
                "title": ["ماجرای <em>نیمروز</em>"]
              },
              "_score": 7.0999684
            }
          ]
        }


## ‌ [/{index_name}/{types}/complete{?text,size,from}]

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه
    + types: `person` (required, string) - فهرست دسته‌ها که با نویسه خط (|) به هم متصل شده‌اند
    + text: `ابراهیم حا` (required, string) - عبارت مورد جستجو
    + size: `10` (optional, number) - تعداد نتایج در پاسخ
    + from: `0` (optional, number) - نقطه شروع برای صفحه‌بندی نتایج

### جستجوی در لحظه [GET]

<div dir=rtl>
تابع جستجوی در لحظه برای استفاده در مواقعی است که با هر بار فشار دادن کلید توسط مخاطب، جستجو انجام می‌شود. در واقع این تابع فرض می‌کند که آخرین کلمه عبارت، هنوز تکمیل نشده است. در این روش، کاربر سریع‌تر به نتیجه مطلوب دست می‌یابد.
</div>

+ Response 200 (application/json)

        {
          "items": [
            {
              "type": "person",
              "id": "1",
              "item": {
                "title": "ابراهیم حاتمی‌کیا",
                "importance": 1,
                "data": {"url": "https://www.filimo.com/crew/ابراهیم_حاتمی_کیا"}
              },
              "highlight": {
                "title": ["<em>ابراهیم حاتمی‌کیا</em>"]
              },
              "_score": 2.5382035
            }
          ]
        }


## ‌ [/{index_name}/{types}/suggest{?text}]

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه
    + types: `movie` (required, string) - فهرست دسته‌ها که با نویسه خط (|) به هم متصل شده‌اند
    + text: `ن` (required, string) - عبارت مورد جستجو

### پیشنهاد جستجو [GET]

<div dir=rtl>
وقتی کاربر در حال نوشتن عبارت مورد نظر است، باز با استفاده از جستجوهای قبلی، تلاش می‌کند به کاربر عبارت مناسبی را برای جستجو پیشنهاد دهد.
</div>

+ Response 200 (application/json)

        {
          "items": [
            {
              "text": "نیم‌روز",
              "count": 2
            }
          ]
        }


## ‌ [/{index_name}/{types}/similars]

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه
    + types: `movie` (required, string) - فهرست دسته‌ها که با نویسه خط (|) به هم متصل شده‌اند

### اسناد مشابه [POST]

<div dir=rtl>
تابع اسناد مشابه، با دریافت اطلاعات مربوط به یک سند، شبیه‌ترین گزینه‌ها را به سند مورد نظر پیدا کرده و میزان تشابه هر کدام را مشخص می‌کند.
</div>

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "title": "پرویز"
            }

+ Response 200 (application/json)

        {
          "items": [
            {
              "title": "پرویز",
              "similarity": 100,
              ...
            },
            ...
          ]
        }


## ‌ [/{index_name}/{types}/sources]

+ Parameters

    + index_name: `baaz` (required, string) - شناسه نمایه
    + types: `movie` (required, string) - فهرست دسته‌ها که با نویسه خط (|) به هم متصل شده‌اند

### اسناد منبع [POST]

<div dir=rtl>
تابع اسناد منبع، با دریافت اطلاعات مربوط به یک سند، منابعی را که این سند با استفاده از آنها درست شده است، پیدا کرده و میزان تشابه را برای هر بخش مشخص می‌کند.
</div>

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "description": "شهر موشها فیلم سینمایی عروسکی تولیدی سال ۱۳۶۴ به کارگردانی سینمایی محمدعلی طالبی و کارگردانی عروسکی مرضیه برومند است. این فیلم سینمایی برای ردهٔ سنی کودکان ساخته شده و عروسک‌های بازیگر آن قبلاً در سریال تلویزیونی مدرسه موش‌ها ایفای نقش کرده بودند."
            }

+ Response 200 (application/json)

        {
          "items": [
            {
              "similarity": 100,
              "src_link": "/baaz/movie/view?id=3",
              "src_title": "شهر موشها",
              "susp_from": 0,
              "susp_to": 247,
              "src_from": 0,
              "src_to": 247,
              "src_text": "شهر موشها فیلم سینمایی عروسکی تولیدی سال ۱۳۶۴ به کارگردانی سینمایی محمدعلی طالبی و کارگردانی عروسکی مرضیه برومند است. این فیلم سینمایی برای ردهٔ سنی کودکان ساخته شده و عروسک‌های بازیگر آن قبلاً در سریال تلویزیونی مدرسه موش‌ها ایفای نقش کرده بودند."
            }
          ]
        }
