
FORMAT: 1A
HOST: http://kashf.sobhe.ir

# کشف

<div dir=rtl>
کشف با دیدن نمونه‌هایی از یک مفهوم در متن، تصویر و یا ویدئو، آن را یاد می‌گیرد و می تواند در داده‌های جدید آن مفهوم را پیدا کند.
</div>

<blockquote dir=rtl>
برای دسترسی به واسط برنامه‌نویس کشف نیاز به یک TOKEN_KEY معتبر دارید که برای احراز هویت استفاده می‌شود. لطفا برای آزمایش سامانه، این متغیر را در تقاضاهای نمونه، جای‌گذاری کنید. سوال هم اگر دارید، لطفا برای آدرس kashf@sobhe.ir بنویسید.
</blockquote>


## تحلیل متن [/api/tag_texts/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "dataset": "digikala",
                "contents": ["ارزش خریدنش رو بی شک داره", "اصلا اصلا کیفیت نداره رنگش بااین عکس زمین تاآسمون فرق داره"]
            }

+ Response 200 (application/json)

        [
          {
            "content": "ارزش خریدنش رو بی شک داره",
            "tags": [
              {
                "id": 39,
                "probability": 1.0,
                "title": "توصیه خرید"
              }
            ]
          },
          {
            "content": "اصلا اصلا کیفیت نداره رنگش بااین عکس زمین تاآسمون فرق داره",
            "tags": [
              {
                "id": 56,
                "probability": 1.0,
                "title": "عدم رضایت بعد خرید"
              }
            ]
          }
        ]


## تحلیل تصویر [/api/tag_images/]

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل تصویر را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "image_file=@example.jpg" -F "dataset=iran" http://kashf.sobhe.ir/api/tag_images

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "dataset": "iran",
                "image_urls": ["https://media.mehrnews.com/d/2016/08/13/4/2171627.jpg", "http://teatreshahr.com/cache/51/attach/201806/254582_2927092954_1000_667.jpg"]
            }

+ Response 200 (application/json)

        [
          {
            "image_url": "https://media.mehrnews.com/d/2016/08/13/4/2171627.jpg",
            "tags": [
              {
                "id": 1,
                "probability": 1.0,
                "title": "حرم رضوی"
              }
            ]
          },
          {
            "image_url": "http://teatreshahr.com/cache/51/attach/201806/254582_2927092954_1000_667.jpg",
            "tags": [
              {
                "id": 36,
                "probability": 1.0,
                "title": "تئاتر شهر"
              }
            ]
          }
        ]


## تحلیل فریم‌های ویدئو [/api/tag_video_frames/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "dataset": "iran",
                "every_ms": 100,
                "duration": 25,
                "min_frame_diff": 50,
                "video_urls": ["https://hw15.cdn.asset.aparat.com/aparat-video/98b7e4cc00c97dffde2ae00567b98a4312759670-480p__79959.mp4"]
            }

+ Response 200 (application/json)

        [
          {
            "video_url": "https://hw15.cdn.asset.aparat.com/aparat-video/98b7e4cc00c97dffde2ae00567b98a4312759670-480p__79959.mp4",
            "frames": [
              {
                "frame": 3,
                "time": "0:00:00",
                "tags": [
                  {
                    "id": 0,
                    "probability": 1.0,
                    "title": "ناآشنا"
                  }
                ]
              },
              {
                "frame": 585,
                "time": "0:00:23",
                "tags": [
                  {
                    "id": 39127,
                    "probability": 0.99,
                    "title": "پل طبیعت"
                  }
                ]
              },
              {
                "frame": 603,
                "time": "0:00:24",
                "tags": [
                  {
                    "id": 2,
                    "probability": 1.0,
                    "title": "میدان آزادی"
                  }
                ]
              }
            ]
          }
        ]


## آموزش مدل [/api/train_dataset/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "dataset": "iran"
            }

+ Response 200 (application/json)

        {
            "dataset": "iran",
            "state": "waiting"
        }


## وضعیت داده‌ها [/api/dataset_info/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
                "dataset": "iran",
                "tags": true
            }

+ Response 200 (application/json)

        {
          "title": "لحظه",
          "state": "trained",
          "report_count": 935,
          "data_count": 2404,
          "evaluation": {
            "recall": 87,
            "precision": 91
          },
          "tags": [
            {
              "title": "برج میلاد"
              "id": 3,
              "reports": 116,
              "predictions": 156,
              "evaluation": {
                "recall": 80.3,
                "precision": 91.4,
                "f1": 86.0
              },
            },
            ...
          ]
        }


## گزارش برچسب متن [/api/report_text_tags/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            [
              {
                "content": "پیشنهاد میکنم از این بخرید خیلی عالیه.",
                "tag_id": 39,
                "positive": true
              }
            ]

+ Response 200 (application/json)

        [
          {
            "report": "[[39,true]]",
            "id": 1211592
          }
        ]



## گزارش برچسب تصویر [/api/report_image_tags/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            [
              {
                "image_url": "https://upload.wikimedia.org/wikipedia/fa/thumb/5/54/Tehran-Milad_Tower2.jpg/800px-Tehran-Milad_Tower2.jpg",
                "tag_id": 3,
                "positive": true
              }
            ]

+ Response 200 (application/json)

        [
          {
            "report": "[[3,true]]",
            "id": 1211593
          }
        ]


## ایجاد برچسب [/api/create_tag/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "dataset": "iran",
              "title": "New Place"
            }

+ Response 200 (application/json)

        {
          "title": "New Place",
          "tag_id": 111111111,
          "active": true
        }


## ویرایش برچسب [/api/update_tag/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "dataset": "iran",
              "tag_id": 111111111,
              "title": "Old Place",
              "active": true
            }

+ Response 200 (application/json)

        {
          "title": "Old Place",
          "tag_id": 111111111,
          "active": true
        }


## حذف برچسب [/api/delete_tag/]

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "tag_id": 111111111
            }

+ Response 200 (application/json)

        {
          "dataset": "iran",
          "deleted_reports": 0
        }
